'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth } from './AuthContext';

// Define supported languages
export type SupportedLanguage = 'en' | 'fr' | 'de' | 'it' | 'es';

// Language labels for display in UI
export const languageLabels: Record<SupportedLanguage, string> = {
  en: 'English',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  es: 'Español',
};

// Add type for user with preferredLanguage
interface UserWithPreferredLanguage {
  id: string;
  email: string;
  preferredLanguage?: SupportedLanguage;
  [key: string]: any; // Allow other properties
}

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
  translate: (key: string, params?: Record<string, string>) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Create translations object (will be populated with actual translations later)
const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    welcome: 'Welcome',
    home: 'Home',
    about: 'About',
    features: 'Features',
    pricing: 'Pricing',
    contact: 'Contact',
    dashboard: 'Dashboard',
    chat: 'Chat',
    documentChat: 'Document Chat',
    profile: 'Your Profile',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    preferredLanguage: 'Preferred Language',
    adminDashboard: 'Admin Dashboard',
    adminDashboardDescription: 'Manage businesses, content, and users from a central location',
    refresh: 'Refresh',
    noBusinessesFound: 'No businesses found',
    loginToAltaCoach: 'Login to AltaCoach',
    welcomeBack: 'Welcome back',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    selectRole: 'Select Role',
    dontHaveAccount: 'Don\'t have an account?',
    selectBusiness: 'Select Business',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    invalidCredentials: 'Invalid email or password',
    error: 'An error occurred. Please try again.',
    language: 'Language',
    password: 'Password',
    // Admin dashboard translations
    businesses: 'Businesses',
    content: 'Content',
    userAccounts: 'User Accounts',
    settings: 'Settings',
    analytics: 'Analytics',
    chatAnalysis: 'Chat Analysis',
    prompts: 'Prompts',
    notifications: 'Notifications',
    businessOverview: 'Business Overview',
    activeBusinesses: 'Active Businesses',
    pendingBusinesses: 'Pending Businesses',
    suspendedBusinesses: 'Suspended Businesses',
    contentManagement: 'Content Management',
    contentItems: 'Content Items',
    exercises: 'Exercises',
    faqs: 'FAQs',
    viewAll: 'View All',
    manage: 'Manage',
    approve: 'Approve',
    suspend: 'Suspend',
    delete: 'Delete',
    userStatistics: 'User Statistics',
    totalBusinesses: 'Total Businesses',
    totalContent: 'Total Content',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    adminUsers: 'Admin Users',
    courses: 'Courses',
    guides: 'Guides',
    recentRegistrations: 'Recent Registrations',
    selectLanguage: 'Select Language',
    name: 'Name',
    plan: 'Plan',
    userCount: 'Users',
    status: 'Status',
    joined: 'Joined',
    actions: 'Actions',
    active: 'Active',
    pending: 'Pending',
    suspended: 'Suspended',
    view: 'View',
    starter: 'Starter',
    business: 'Business',
    enterprise: 'Enterprise',
    businessAddedSuccessfully: 'Business added successfully!',
    errorAddingBusiness: 'Error adding business. Please try again later.',
    businessName: 'Business Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    address: 'Address',
    submitting: 'Submitting...',
    add: 'Add',
    cancel: 'Cancel',
    // Settings page translations
    admin: 'Admin',
    settingsDescription: 'Configure platform settings and manage system preferences',
    general: 'General',
    aiPrompts: 'AI Prompts',
    apiKeys: 'API Keys',
    generalSettings: 'General Settings',
    configureGeneralSettings: 'Configure your platform general settings.',
    generalSettingsFutureUpdate: 'Platform general settings will be available here in a future update.',
    aiPromptsManagement: 'AI Prompts Management',
    addNewPrompt: 'Add New Prompt',
    description: 'Description',
    lastUpdated: 'Last Updated',
    noDescription: 'No description',
    inactive: 'Inactive',
    deactivate: 'Deactivate',
    activate: 'Activate',
    noPromptsFound: 'No prompts found. Add your first prompt to get started.',
    apiIntegration: 'API Integration',
    configureApiKeys: 'Configure API keys for third-party service integrations.',
    openaiApiKey: 'OpenAI API Key',
    openaiApiDescription: 'Configure your OpenAI API key to enable AI capabilities. Without this, AI capabilities will be limited.',
    configureApiKey: 'Configure API Key',
    additionalIntegrations: 'Additional Integrations',
    moreIntegrationsFuture: 'More third-party integrations will be available in future updates.',
    configureOpenaiApiKey: 'Configure OpenAI API Key',
    apiKey: 'API Key',
    enterApiKeySecure: 'Enter your OpenAI API key. This will be stored securely.',
    saving: 'Saving...',
    saveApiKey: 'Save API Key',
    createNewAiPrompt: 'Create New AI Prompt',
    promptName: 'Prompt Name',
    descriptionOptional: 'Description (Optional)',
    briefDescriptionPrompt: 'Brief description of prompt purpose',
    promptContent: 'Prompt Content',
    promptPlaceholder: 'You are an AI assistant that helps with...',
    systemPromptGuide: 'This is the system prompt that will guide the AI behavior.',
    setAsActivePrompt: 'Set as active prompt',
    oneActivePromptWarning: 'Only one prompt can be active at a time. Setting this as active will deactivate other prompts.',
    creating: 'Creating...',
    createPrompt: 'Create Prompt',
    apiKeyCannotBeEmpty: 'API key cannot be empty',
    apiKeySetSuccess: 'API key set successfully',
    failedToSetApiKey: 'Failed to set API key',
    promptNameRequired: 'Prompt name is required',
    promptContentRequired: 'Prompt content is required',
    failedToCreatePrompt: 'Failed to create prompt',
    promptCreatedSuccess: 'Prompt created successfully',
    failedToFetchPrompts: 'Failed to fetch prompts',
    failedToLoadPrompts: 'Failed to load prompts. Please try again later.',
    confirmDeletePrompt: 'Are you sure you want to delete this prompt? This action cannot be undone.',
    failedToDeletePrompt: 'Failed to delete prompt',
    confirmDeactivatePrompt: 'Are you sure you want to deactivate this prompt?',
    confirmActivatePrompt: 'Activating this prompt will deactivate any currently active prompt. Continue?',
    failedToUpdatePrompt: 'Failed to update prompt',
    systemInstructions: 'System Instructions',
    // Main page translations
    trainingDoesntEnd: 'Training Doesn\'t End in the Classroom',
    aiPoweredAssistant: 'AltaCoach is your AI-powered assistant for post-training support, helping employees apply what they learned and boost retention.',
    tryAltaCoach: 'Try AltaCoach',
    viewPricing: 'View Pricing',
    postTrainingSupport: 'Post-Training Support',
    realTimeCoaching: 'Real-Time Coaching',
    knowledgeRetention: 'Knowledge Retention',
    howReinforces: 'How AltaCoach Reinforces Training',
    aiPoweredPlatform: 'Our AI-powered platform provides continuous support after formal training ends.',
    aiPoweredQA: 'AI-Powered Q&A',
    employeesCanAsk: 'Employees can ask questions and get immediate, accurate answers based on your training materials.',
    contentIntegration: 'Content Integration',
    seamlesslyIntegrates: 'Seamlessly integrates with your existing training content and documentation.',
    analyticsInsights: 'Analytics & Insights',
    trackEngagement: 'Track engagement, identify knowledge gaps, and measure the impact of your training initiatives.',
    improvedRetention: 'Improved Retention',
    increaseKnowledge: 'Increase in knowledge retention compared to traditional training methods',
    timeSaved: 'Time Saved',
    reductionSearching: 'Reduction in time spent searching for information',
    userSatisfaction: 'User Satisfaction',
    positiveFeedback: 'Positive feedback from employees using the platform',
    readyTransform: 'Ready to Transform Your Training?',
    joinOrganizations: 'Join organizations using AltaCoach to boost training retention and performance.',
    getStarted: 'Get Started',
    quickAccess: 'Quick Access',
    noLoginRequired: 'No Login Required',
    startSession: 'Start Session',
    // Contact page translations
    getInTouch: 'Get in Touch',
    thankYouMessage: 'Thank you for your message! We\'ll get back to you as soon as possible.',
    contactDescription: 'Have questions or want to learn more about AltaCoach? Fill out the form below and our team will respond shortly.',
    yourName: 'Your name',
    emailAddress: 'Email address',
    subject: 'Subject',
    message: 'Your message',
    sending: 'Sending...',
    sendMessage: 'Send Message',
    errorSubmittingMessage: 'An error occurred while submitting your message. Please try again.',
    
    // Pricing page translations
    choosePerfectPlan: 'Choose the perfect plan for your needs. All plans include access to our core AI coaching features.',
    basic: 'Basic',
    professional: 'Professional',
    forIndividuals: 'For individual professionals',
    forGrowingProfessionals: 'For growing professionals',
    forLargeOrganizations: 'For teams and organizations',
    month: 'month',
    mostPopular: 'MOST POPULAR',
    unlimitedAiConversations: 'Unlimited AI conversations',
    uploadUpTo10Documents: 'Upload up to 10 documents',
    uploadUpTo50Documents: 'Upload up to 50 documents',
    unlimitedDocuments: 'Unlimited document uploads',
    basicProgressTracking: 'Basic progress tracking',
    emailSupport: 'Email support',
    everythingInBasic: 'Everything in Basic',
    everythingInProfessional: 'Everything in Professional',
    prioritySupport: 'Priority support',
    dedicatedSupport: 'Dedicated support',
    customIntegration: 'Custom integration',
    contactUs: 'Contact Us',
    custom: 'Custom',
    
    // FAQ translations
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    canICancel: 'Can I cancel my subscription at any time?',
    yesYouCan: 'Yes, you can cancel your subscription at any time. Changes will be reflected in your next billing cycle.',
    howManyUsers: 'How many users can I add to my plan?',
    basicAndProfessionalPlans: 'Basic and Professional plans are for individual use. For teams, please consider our Enterprise plan.',
    whatTypesOfDocuments: 'What types of documents does AltaCoach support?',
    altaCoachSupports: 'AltaCoach supports PDF, DOCX, PPT, CSV, and text files. More formats will be added in future updates.',
    isMyDataSecure: 'Is my data secure?',
    absolutelyWeTake: 'Absolutely! We take data security seriously. All your documents and conversations are encrypted and stored securely.',
    
    // Other missing translations
    phone: 'Phone',
    location: 'Location',
    
    // Features page translations
    aiPoweredConversations: 'AI-Powered Conversations',
    engageInNatural: 'Engage in natural conversations with our AI assistant to reinforce your training concepts and answer questions in real-time.',
    documentBasedLearning: 'Document-Based Learning',
    uploadTrainingMaterials: 'Upload your training materials and let AltaCoach process them to provide relevant information and answers from your content.',
    continuousReinforcement: 'Continuous Reinforcement',
    receiveRegularPrompts: 'Receive regular prompts and challenges to reinforce what you have learned and keep knowledge fresh over time.',
    progressTracking: 'Progress Tracking',
    monitorYourLearning: 'Monitor your learning journey with comprehensive analytics that show engagement and knowledge retention.',
    howAltaCoachWorks: 'How AltaCoach Works',
    uploadYourMaterials: 'Upload Your Materials',
    addYourTrainingDocuments: 'Add your training documents to create a knowledge base for the AI to reference.',
    engageWithYourCoach: 'Engage With Your Coach',
    askQuestions: 'Ask questions and get immediate, personalized responses based on your materials.',
    reinforceAndImprove: 'Reinforce and Improve',
    receivePersonalizedChallenges: 'Receive personalized challenges and prompts to strengthen knowledge retention.',
    enterpriseFeatures: 'Enterprise Features',
    teamManagement: 'Team Management',
    createAndManageLearningGroups: 'Create and manage learning groups to track team progress collectively.',
    connectAltaCoach: 'Connect AltaCoach with your existing learning management systems.',
    advancedAnalytics: 'Advanced Analytics',
    gainInsights: 'Gain insights into learning patterns and identify knowledge gaps across teams.',
    customizedLearningPaths: 'Customized Learning Paths',
    designTailoredLearning: 'Design tailored learning experiences for different roles and departments.',
    currentLanguage: 'Current Language',
  },
  fr: {
    welcome: 'Bienvenue',
    home: 'Accueil',
    about: 'À propos',
    features: 'Fonctionnalités',
    pricing: 'Tarifs',
    contact: 'Contact',
    dashboard: 'Tableau de bord',
    chat: 'Discuter',
    documentChat: 'Chat de Document',
    profile: 'Votre Profil',
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    signOut: 'Se déconnecter',
    preferredLanguage: 'Langue préférée',
    adminDashboard: 'Tableau de Bord Admin',
    adminDashboardDescription: 'Gérez les entreprises, le contenu et les utilisateurs depuis un emplacement central',
    refresh: 'Rafraîchir',
    noBusinessesFound: 'Aucune entreprise trouvée',
    loginToAltaCoach: 'Connexion à AltaCoach',
    welcomeBack: 'Bienvenue',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    selectRole: 'Sélectionner un Rôle',
    dontHaveAccount: "Vous n'avez pas de compte ?",
    selectBusiness: 'Sélectionner une Entreprise',
    emailRequired: "L'email est requis",
    passwordRequired: 'Le mot de passe est requis',
    invalidCredentials: 'Email ou mot de passe invalide',
    error: "Une erreur s'est produite. Veuillez réessayer.",
    language: 'Langue',
    password: 'Mot de passe',
    // Admin dashboard translations
    businesses: 'Entreprises',
    content: 'Contenu',
    userAccounts: 'Comptes Utilisateurs',
    settings: 'Paramètres',
    analytics: 'Analytiques',
    chatAnalysis: 'Analyse de Chat',
    prompts: 'Invites',
    notifications: 'Notifications',
    businessOverview: 'Aperçu des Entreprises',
    activeBusinesses: 'Entreprises Actives',
    pendingBusinesses: 'Entreprises en Attente',
    suspendedBusinesses: 'Entreprises Suspendues',
    contentManagement: 'Gestion de Contenu',
    contentItems: 'Éléments de Contenus',
    exercises: 'Exercices',
    faqs: 'FAQs',
    viewAll: 'Voir Tout',
    manage: 'Gérer',
    approve: 'Approuver',
    suspend: 'Suspendre',
    delete: 'Supprimer',
    userStatistics: 'Statistiques Utilisateurs',
    totalBusinesses: 'Total des Entreprises',
    totalContent: 'Total du Contenu',
    totalUsers: 'Total des Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    adminUsers: 'Utilisateurs Admin',
    courses: 'Cours',
    guides: 'Guides',
    recentRegistrations: 'Inscriptions Récentes',
    selectLanguage: 'Sélectionner la Langue',
    name: 'Nom',
    plan: 'Plan',
    userCount: 'Utilisateurs',
    status: 'État',
    joined: 'Rejoint',
    actions: 'Actions',
    active: 'Actif',
    pending: 'En attente',
    suspended: 'Suspendu',
    view: 'Voir',
    starter: 'Débutant',
    business: 'Entreprise',
    enterprise: 'Enterprise',
    businessAddedSuccessfully: 'Entreprise ajoutée avec succès !',
    errorAddingBusiness: 'Erreur lors de l\'ajout de l\'entreprise. Veuillez réessayer plus tard.',
    businessName: 'Nom de l\'Entreprise',
    email: 'Email',
    phoneNumber: 'Téléphone',
    address: 'Adresse',
    submitting: 'Envoi...',
    add: 'Ajouter',
    cancel: 'Annuler',
    // Settings page translations
    admin: 'Admin',
    settingsDescription: 'Configurer les paramètres de la plateforme et gérer les préférences du système',
    general: 'Général',
    aiPrompts: 'Invites IA',
    apiKeys: 'Clés API',
    generalSettings: 'Paramètres Généraux',
    configureGeneralSettings: 'Configurez les paramètres généraux de votre plateforme.',
    generalSettingsFutureUpdate: 'Les paramètres généraux de la plateforme seront disponibles ici dans une future mise à jour.',
    aiPromptsManagement: 'Gestion des Invites IA',
    addNewPrompt: 'Ajouter une Nouvelle Invite',
    description: 'Description',
    lastUpdated: 'Dernière Mise à Jour',
    noDescription: 'Pas de description',
    inactive: 'Inactif',
    deactivate: 'Désactiver',
    activate: 'Activer',
    noPromptsFound: 'Aucune invite trouvée. Ajoutez votre première invite pour commencer.',
    apiIntegration: 'Intégration API',
    configureApiKeys: 'Configurez les clés API pour les intégrations de services tiers.',
    openaiApiKey: 'Clé API OpenAI',
    openaiApiDescription: 'Configurez votre clé API OpenAI pour activer les fonctionnalités d\'IA. Sans cela, les capacités d\'IA seront limitées.',
    configureApiKey: 'Configurer la Clé API',
    additionalIntegrations: 'Intégrations Supplémentaires',
    moreIntegrationsFuture: 'D\'autres intégrations tierces seront disponibles dans les futures mises à jour.',
    configureOpenaiApiKey: 'Configurer la Clé API OpenAI',
    apiKey: 'Clé API',
    enterApiKeySecure: 'Entrez votre clé API OpenAI. Elle sera stockée en toute sécurité.',
    saving: 'Enregistrement...',
    saveApiKey: 'Enregistrer la Clé API',
    createNewAiPrompt: 'Créer une Nouvelle Invite IA',
    promptName: 'Nom de l\'Invite',
    descriptionOptional: 'Description (Optionnelle)',
    briefDescriptionPrompt: 'Brève description de l\'objectif de l\'invite',
    promptContent: 'Contenu de l\'Invite',
    promptPlaceholder: 'Vous êtes un assistant IA qui aide avec...',
    systemPromptGuide: 'Ceci est l\'invite système qui guidera le comportement de l\'IA.',
    setAsActivePrompt: 'Définir comme invite active',
    oneActivePromptWarning: 'Une seule invite peut être active à la fois. Définir celle-ci comme active désactivera les autres invites.',
    creating: 'Création...',
    createPrompt: 'Créer l\'Invite',
    apiKeyCannotBeEmpty: 'La clé API ne peut pas être vide',
    apiKeySetSuccess: 'Clé API définie avec succès',
    failedToSetApiKey: 'Échec de la définition de la clé API',
    promptNameRequired: 'Le nom de l\'invite est requis',
    promptContentRequired: 'Le contenu de l\'invite est requis',
    failedToCreatePrompt: 'Échec de la création de l\'invite',
    promptCreatedSuccess: 'Invite créée avec succès',
    failedToFetchPrompts: 'Échec de la récupération des invites',
    failedToLoadPrompts: 'Échec du chargement des invites. Veuillez réessayer plus tard.',
    confirmDeletePrompt: 'Êtes-vous sûr de vouloir supprimer cette invite ? Cette action ne peut pas être annulée.',
    failedToDeletePrompt: 'Échec de la suppression de l\'invite',
    confirmDeactivatePrompt: 'Êtes-vous sûr de vouloir désactiver cette invite ?',
    confirmActivatePrompt: 'L\'activation de cette invite désactivera toute invite actuellement active. Continuer ?',
    failedToUpdatePrompt: 'Échec de la mise à jour de l\'invite',
    systemInstructions: 'Instructions Système',
    // Main page translations
    trainingDoesntEnd: 'La Formation Ne S\'arrête Pas en Classe',
    aiPoweredAssistant: 'AltaCoach est votre assistant propulsé par l\'IA pour le soutien post-formation, aidant les employés à appliquer ce qu\'ils ont appris et augmentant la rétention.',
    tryAltaCoach: 'Essayer AltaCoach',
    viewPricing: 'Voir les tarifs',
    postTrainingSupport: 'Support Post-Formation',
    realTimeCoaching: 'Coaching en Temps Réel',
    knowledgeRetention: 'Rétention des Connaissances',
    howReinforces: 'Comment AltaCoach Renforce la Formation',
    aiPoweredPlatform: 'Notre plateforme propulsée par l\'IA fournit un soutien continu après la fin de la formation formelle.',
    aiPoweredQA: 'AI-Powered Q&A',
    employeesCanAsk: 'Les employés peuvent poser des questions et obtenir des réponses instantanées et précises basées sur votre matériel de formation.',
    contentIntegration: 'Intégration de Contenu',
    seamlesslyIntegrates: 'S\'intègre parfaitement à votre contenu de formation et documentation existants.',
    analyticsInsights: 'Analyses et Insights',
    trackEngagement: 'Suivez l\'engagement, identifiez les lacunes de connaissances et mesurez l\'impact de vos initiatives de formation.',
    improvedRetention: 'Rétention Améliorée',
    increaseKnowledge: 'Augmentation de la rétention des connaissances par rapport aux méthodes de formation traditionnelles',
    timeSaved: 'Temps Économisé',
    reductionSearching: 'Réduction du temps passé à rechercher des informations',
    userSatisfaction: 'Satisfaction des Utilisateurs',
    positiveFeedback: 'Retours positifs des employés utilisant la plateforme',
    readyTransform: 'Prêt à transformer votre formation ?',
    joinOrganizations: 'Rejoignez les organisations qui utilisent AltaCoach pour améliorer la rétention et la performance de la formation.',
    getStarted: 'Commencer',
    quickAccess: 'Accès Rapide',
    noLoginRequired: 'Aucune Connexion Requise',
    startSession: 'Démarrer la Session',
    // Contact page translations
    getInTouch: 'Contactez-nous',
    thankYouMessage: 'Merci pour votre message! Nous vous répondrons dès que possible.',
    contactDescription: 'Vous avez des questions ou souhaitez en savoir plus sur AltaCoach? Remplissez le formulaire ci-dessous et notre équipe vous répondra rapidement.',
    yourName: 'Votre nom',
    emailAddress: 'Adresse e-mail',
    subject: 'Sujet',
    message: 'Votre message',
    sending: 'Envoi en cours...',
    sendMessage: 'Envoyer le message',
    errorSubmittingMessage: 'Une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer.',
    
    // Pricing page translations
    choosePerfectPlan: 'Choisissez le forfait parfait pour vos besoins. Tous les forfaits comprennent l\'accès à nos fonctionnalités principales de coaching par IA.',
    basic: 'Basique',
    professional: 'Professionnel',
    forIndividuals: 'Pour les professionnels individuels',
    forGrowingProfessionals: 'Pour les professionnels en croissance',
    forLargeOrganizations: 'Pour les grandes organisations',
    month: 'mois',
    mostPopular: 'LE PLUS POPULAIRE',
    unlimitedAiConversations: 'Conversations IA illimitées',
    uploadUpTo10Documents: 'Téléchargement jusqu\'à 10 documents',
    uploadUpTo50Documents: 'Téléchargement jusqu\'à 50 documents',
    unlimitedDocuments: 'Téléchargement de documents illimité',
    basicProgressTracking: 'Suivi de progression basique',
    emailSupport: 'Support par e-mail',
    everythingInBasic: 'Tout ce qui est inclus dans Basique',
    everythingInProfessional: 'Tout ce qui est inclus dans Professionnel',
    prioritySupport: 'Support prioritaire',
    dedicatedSupport: 'Support dédié',
    customIntegration: 'Intégration personnalisée',
    contactUs: 'Contactez-nous',
    
    // Features page translations
    aiPoweredConversations: 'Conversations Alimentées par l\'IA',
    engageInNatural: 'Engagez des conversations naturelles avec notre assistant IA pour renforcer vos concepts de formation et répondre aux questions en temps réel.',
    documentBasedLearning: 'Apprentissage Basé sur les Documents',
    uploadTrainingMaterials: 'Téléchargez vos supports de formation et laissez AltaCoach les traiter pour fournir des informations et des réponses pertinentes à partir de votre contenu.',
    continuousReinforcement: 'Renforcement Continu',
    receiveRegularPrompts: 'Recevez des incitations et des défis réguliers pour renforcer ce que vous avez appris et maintenir les connaissances fraîches au fil du temps.',
    progressTracking: 'Suivi de Progression',
    monitorYourLearning: 'Suivez votre parcours d\'apprentissage avec des analyses complètes qui montrent l\'engagement et la rétention des connaissances.',
    howAltaCoachWorks: 'Comment Fonctionne AltaCoach',
    uploadYourMaterials: 'Téléchargez Vos Documents',
    addYourTrainingDocuments: 'Ajoutez vos documents de formation pour créer une base de connaissances à laquelle l\'IA peut se référer.',
    engageWithYourCoach: 'Interagissez Avec Votre Coach',
    askQuestions: 'Posez des questions et obtenez des réponses immédiates et personnalisées basées sur vos documents.',
    reinforceAndImprove: 'Renforcez et Améliorez',
    receivePersonalizedChallenges: 'Recevez des défis et des incitations personnalisés pour renforcer la rétention des connaissances.',
    enterpriseFeatures: 'Fonctionnalités Entreprise',
    teamManagement: 'Gestion d\'Équipe',
    createAndManageLearningGroups: 'Créez et gérez des groupes d\'apprentissage pour suivre collectivement les progrès de l\'équipe.',
    connectAltaCoach: 'Connectez AltaCoach à vos systèmes de gestion d\'apprentissage existants.',
    advancedAnalytics: 'Analyses Avancées',
    gainInsights: 'Obtenez des informations sur les modèles d\'apprentissage et identifiez les lacunes de connaissances au sein des équipes.',
    customizedLearningPaths: 'Parcours d\'Apprentissage Personnalisés',
    designTailoredLearning: 'Concevez des expériences d\'apprentissage sur mesure pour différents rôles et départements.',
    currentLanguage: 'Langue Actuelle',
  },
  de: {
    welcome: 'Willkommen',
    home: 'Startseite',
    about: 'Über uns',
    features: 'Funktionen',
    pricing: 'Preise',
    contact: 'Kontakt',
    dashboard: 'Dashboard',
    chat: 'Chat',
    documentChat: 'Dokument-Chat',
    profile: 'Dein Profil',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    preferredLanguage: 'Bevorzugte Sprache',
    adminDashboard: 'Admin-Dashboard',
    adminDashboardDescription: 'Verwalten Sie Unternehmen, Inhalte und Benutzer von einem zentralen Ort aus',
    refresh: 'Aktualisieren',
    noBusinessesFound: 'Keine Unternehmen gefunden',
    loginToAltaCoach: 'Bei AltaCoach anmelden',
    welcomeBack: 'Willkommen zurück',
    rememberMe: 'Angemeldet bleiben',
    forgotPassword: 'Passwort vergessen?',
    selectRole: 'Rolle auswählen',
    dontHaveAccount: 'Noch kein Konto?',
    selectBusiness: 'Unternehmen auswählen',
    emailRequired: 'E-Mail ist erforderlich',
    passwordRequired: 'Passwort ist erforderlich',
    invalidCredentials: 'Ungültige E-Mail oder Passwort',
    error: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    language: 'Sprache',
    password: 'Passwort',
    // FAQ translations
    frequentlyAskedQuestions: 'Häufig Gestellte Fragen',
    canICancel: 'Kann ich mein Abonnement jederzeit kündigen?',
    yesYouCan: 'Ja, Sie können Ihr Abonnement jederzeit kündigen. Änderungen werden in Ihrem nächsten Abrechnungszyklus angezeigt.',
    howManyUsers: 'Wie viele Benutzer kann ich zu meinem Plan hinzufügen?',
    basicAndProfessionalPlans: 'Basic- und Professional-Pläne sind für die individuelle Nutzung gedacht. Für Teams empfehlen wir unseren Enterprise-Plan.',
    whatTypesOfDocuments: 'Welche Dokumenttypen unterstützt AltaCoach?',
    altaCoachSupports: 'AltaCoach unterstützt PDF-, DOCX-, PPT-, CSV- und Textdateien. Weitere Formate werden in zukünftigen Updates hinzugefügt.',
    isMyDataSecure: 'Sind meine Daten sicher?',
    absolutelyWeTake: 'Absolut! Wir nehmen Datensicherheit ernst. Alle Ihre Dokumente und Gespräche werden verschlüsselt und sicher gespeichert.',
    
    // Other missing translations
    custom: 'Individuell',
    forLargeOrganizations: 'Für große Organisationen',
    customIntegration: 'Benutzerdefinierte Integration',
    customizableFeatures: 'Anpassbare Funktionen',
    phone: 'Telefon',
    location: 'Standort',
    
    // Additional German translations
    businesses: 'Unternehmen',
    content: 'Inhalt',
    userAccounts: 'Benutzerkonten',
    settings: 'Einstellungen',
    analytics: 'Analytik',
    chatAnalysis: 'Chat Analyse',
    prompts: 'Prompts',
    notifications: 'Benachrichtigungen',
    businessOverview: 'Aperçu des Entreprises',
    activeBusinesses: 'Entreprises Actives',
    pendingBusinesses: 'Entreprises en Attente',
    suspendedBusinesses: 'Entreprises Suspendues',
    contentManagement: 'Gestion de Contenu',
    contentItems: 'Éléments de Contenus',
    exercises: 'Exercices',
    faqs: 'FAQs',
    viewAll: 'Voir Tout',
    manage: 'Gérer',
    approve: 'Approuver',
    suspend: 'Suspendre',
    delete: 'Supprimer',
    userStatistics: 'Statistiques Utilisateurs',
    totalBusinesses: 'Total des Entreprises',
    totalContent: 'Total du Contenu',
    totalUsers: 'Total des Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    adminUsers: 'Utilisateurs Admin',
    courses: 'Cours',
    guides: 'Guides',
    recentRegistrations: 'Inscriptions Récentes',
    selectLanguage: 'Sélectionner la Langue',
    name: 'Nom',
    plan: 'Plan',
    userCount: 'Utilisateurs',
    status: 'État',
    joined: 'Rejoint',
    actions: 'Actions',
    active: 'Actif',
    pending: 'En attente',
    suspended: 'Suspendu',
    view: 'Voir',
    starter: 'Débutant',
    business: 'Entreprise',
    enterprise: 'Enterprise',
    businessAddedSuccessfully: 'Entreprise ajoutée avec succès !',
    errorAddingBusiness: 'Erreur lors de l\'ajout de l\'entreprise. Veuillez réessayer plus tard.',
    businessName: 'Nom de l\'Entreprise',
    email: 'Email',
    phoneNumber: 'Téléphone',
    address: 'Adresse',
    submitting: 'Envoi...',
    add: 'Ajouter',
    cancel: 'Annuler',
    // Settings page translations
    admin: 'Admin',
    settingsDescription: 'Configurer les paramètres de la plateforme et gérer les préférences du système',
    general: 'Général',
    aiPrompts: 'Invites IA',
    apiKeys: 'Clés API',
    generalSettings: 'Paramètres Généraux',
    configureGeneralSettings: 'Configurez les paramètres généraux de votre plateforme.',
    generalSettingsFutureUpdate: 'Les paramètres généraux de la plateforme seront disponibles ici dans une future mise à jour.',
    aiPromptsManagement: 'Gestion des Invites IA',
    addNewPrompt: 'Ajouter une Nouvelle Invite',
    description: 'Description',
    lastUpdated: 'Dernière Mise à Jour',
    noDescription: 'Pas de description',
    inactive: 'Inactif',
    deactivate: 'Désactiver',
    activate: 'Activer',
    noPromptsFound: 'Aucune invite trouvée. Ajoutez votre première invite pour commencer.',
    apiIntegration: 'Intégration API',
    configureApiKeys: 'Configurez les clés API pour les intégrations de services tiers.',
    openaiApiKey: 'Clé API OpenAI',
    openaiApiDescription: 'Configurez votre clé API OpenAI pour activer les fonctionnalités d\'IA. Sans cela, les capacités d\'IA seront limitées.',
    configureApiKey: 'Configurer la Clé API',
    additionalIntegrations: 'Intégrations Supplémentaires',
    moreIntegrationsFuture: 'D\'autres intégrations tierces seront disponibles dans les futures mises à jour.',
    configureOpenaiApiKey: 'Configurer la Clé API OpenAI',
    apiKey: 'Clé API',
    enterApiKeySecure: 'Entrez votre clé API OpenAI. Elle sera stockée en toute sécurité.',
    saving: 'Enregistrement...',
    saveApiKey: 'Enregistrer la Clé API',
    createNewAiPrompt: 'Créer une Nouvelle Invite IA',
    promptName: 'Nom de l\'Invite',
    descriptionOptional: 'Description (Optionnelle)',
    briefDescriptionPrompt: 'Brève description de l\'objectif de l\'invite',
    promptContent: 'Contenu de l\'Invite',
    promptPlaceholder: 'Vous êtes un assistant IA qui aide avec...',
    systemPromptGuide: 'Ceci est l\'invite système qui guidera le comportement de l\'IA.',
    setAsActivePrompt: 'Définir comme invite active',
    oneActivePromptWarning: 'Une seule invite peut être active à la fois. Définir celle-ci comme active désactivera les autres invites.',
    creating: 'Création...',
    createPrompt: 'Créer l\'Invite',
    apiKeyCannotBeEmpty: 'La clé API ne peut pas être vide',
    apiKeySetSuccess: 'Clé API définie avec succès',
    failedToSetApiKey: 'Échec de la définition de la clé API',
    promptNameRequired: 'Le nom de l\'invite est requis',
    promptContentRequired: 'Le contenu de l\'invite est requis',
    failedToCreatePrompt: 'Échec de la création de l\'invite',
    promptCreatedSuccess: 'Invite créée avec succès',
    failedToFetchPrompts: 'Échec de la récupération des invites',
    failedToLoadPrompts: 'Échec du chargement des invites. Veuillez réessayer plus tard.',
    confirmDeletePrompt: 'Êtes-vous sûr de vouloir supprimer cette invite ? Cette action ne peut pas être annulée.',
    failedToDeletePrompt: 'Échec de la suppression de l\'invite',
    confirmDeactivatePrompt: 'Êtes-vous sûr de vouloir désactiver cette invite ?',
    confirmActivatePrompt: 'L\'activation de cette invite désactivera toute invite actuellement active. Continuer ?',
    failedToUpdatePrompt: 'Échec de la mise à jour de l\'invite',
    systemInstructions: 'Instructions Système',
    // Main page translations
    trainingDoesntEnd: 'La Formation Ne S\'arrête Pas en Classe',
    aiPoweredAssistant: 'AltaCoach est votre assistant propulsé par l\'IA pour le soutien post-formation, aidant les employés à appliquer ce qu\'ils ont appris et augmentant la rétention.',
    tryAltaCoach: 'Essayer AltaCoach',
    viewPricing: 'Voir les tarifs',
    postTrainingSupport: 'Support Post-Formation',
    realTimeCoaching: 'Coaching en Temps Réel',
    knowledgeRetention: 'Rétention des Connaissances',
    howReinforces: 'Comment AltaCoach Renforce la Formation',
    aiPoweredPlatform: 'Notre plateforme propulsée par l\'IA fournit un soutien continu après la fin de la formation formelle.',
    aiPoweredQA: 'AI-Powered Q&A',
    employeesCanAsk: 'Les employés peuvent poser des questions et obtenir des réponses instantanées et précises basées sur votre matériel de formation.',
    contentIntegration: 'Intégration de Contenu',
    seamlesslyIntegrates: 'S\'intègre parfaitement à votre contenu de formation et documentation existants.',
    analyticsInsights: 'Analyses et Insights',
    trackEngagement: 'Suivez l\'engagement, identifiez les lacunes de connaissances et mesurez l\'impact de vos initiatives de formation.',
    improvedRetention: 'Rétention Améliorée',
    increaseKnowledge: 'Augmentation de la rétention des connaissances par rapport aux méthodes de formation traditionnelles',
    timeSaved: 'Temps Économisé',
    reductionSearching: 'Réduction du temps passé à rechercher des informations',
    userSatisfaction: 'Satisfaction des Utilisateurs',
    positiveFeedback: 'Retours positifs des employés utilisant la plateforme',
    readyTransform: 'Prêt à transformer votre formation ?',
    joinOrganizations: 'Rejoignez les organisations qui utilisent AltaCoach pour améliorer la rétention et la performance de la formation.',
    getStarted: 'Commencer',
    quickAccess: 'Accès Rapide',
    noLoginRequired: 'Aucune Connexion Requise',
    startSession: 'Démarrer la Session',
    // Contact page translations
    getInTouch: 'Contactez-nous',
    thankYouMessage: 'Merci pour votre message! Nous vous répondrons dès que possible.',
    contactDescription: 'Vous avez des questions ou souhaitez en savoir plus sur AltaCoach? Remplissez le formulaire ci-dessous et notre équipe vous répondra rapidement.',
    yourName: 'Votre nom',
    emailAddress: 'Adresse e-mail',
    subject: 'Sujet',
    message: 'Votre message',
    sending: 'Envoi en cours...',
    sendMessage: 'Envoyer le message',
    errorSubmittingMessage: 'Une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer.',
    
    // Pricing page translations
    choosePerfectPlan: 'Choisissez le forfait parfait pour vos besoins. Tous les forfaits comprennent l\'accès à nos fonctionnalités principales de coaching par IA.',
    basic: 'Basique',
    professional: 'Professionnel',
    forIndividuals: 'Pour les professionnels individuels',
    forGrowingProfessionals: 'Pour les professionnels en croissance',
    forLargeOrganizations: 'Pour les grandes organisations',
    month: 'mois',
    mostPopular: 'LE PLUS POPULAIRE',
    unlimitedAiConversations: 'Conversations IA illimitées',
    uploadUpTo10Documents: 'Téléchargement jusqu\'à 10 documents',
    uploadUpTo50Documents: 'Téléchargement jusqu\'à 50 documents',
    unlimitedDocuments: 'Téléchargement de documents illimité',
    basicProgressTracking: 'Suivi de progression basique',
    emailSupport: 'Support par e-mail',
    everythingInBasic: 'Tout ce qui est inclus dans Basique',
    everythingInProfessional: 'Tout ce qui est inclus dans Professionnel',
    prioritySupport: 'Support prioritaire',
    dedicatedSupport: 'Support dédié',
    customIntegration: 'Intégration personnalisée',
    contactUs: 'Contactez-nous',
    
    // Features page translations
    aiPoweredConversations: 'Conversations Alimentées par l\'IA',
    engageInNatural: 'Engagez des conversations naturelles avec notre assistant IA pour renforcer vos concepts de formation et répondre aux questions en temps réel.',
    documentBasedLearning: 'Apprentissage Basé sur les Documents',
    uploadTrainingMaterials: 'Téléchargez vos supports de formation et laissez AltaCoach les traiter pour fournir des informations et des réponses pertinentes à partir de votre contenu.',
    continuousReinforcement: 'Renforcement Continu',
    receiveRegularPrompts: 'Recevez des incitations et des défis réguliers pour renforcer ce que vous avez appris et maintenir les connaissances fraîches au fil du temps.',
    progressTracking: 'Suivi de Progression',
    monitorYourLearning: 'Suivez votre parcours d\'apprentissage avec des analyses complètes qui montrent l\'engagement et la rétention des connaissances.',
    howAltaCoachWorks: 'Comment Fonctionne AltaCoach',
    uploadYourMaterials: 'Téléchargez Vos Documents',
    addYourTrainingDocuments: 'Ajoutez vos documents de formation pour créer une base de connaissances à laquelle l\'IA peut se référer.',
    engageWithYourCoach: 'Interagissez Avec Votre Coach',
    askQuestions: 'Posez des questions et obtenez des réponses immédiates et personnalisées basées sur vos documents.',
    reinforceAndImprove: 'Renforcez et Améliorez',
    receivePersonalizedChallenges: 'Recevez des défis et des incitations personnalisés pour renforcer la rétention des connaissances.',
    enterpriseFeatures: 'Fonctionnalités Entreprise',
    teamManagement: 'Gestion d\'Équipe',
    createAndManageLearningGroups: 'Créez et gérez des groupes d\'apprentissage pour suivre collectivement les progrès de l\'équipe.',
    connectAltaCoach: 'Connectez AltaCoach à vos systèmes de gestion d\'apprentissage existants.',
    advancedAnalytics: 'Analyses Avancées',
    gainInsights: 'Obtenez des informations sur les modèles d\'apprentissage et identifiez les lacunes de connaissances au sein des équipes.',
    customizedLearningPaths: 'Parcours d\'Apprentissage Personnalisés',
    designTailoredLearning: 'Concevez des expériences d\'apprentissage sur mesure pour différents rôles et départements.',
    currentLanguage: 'Langue Actuelle',
  },
  it: {
    welcome: 'Benvenuto',
    home: 'Home',
    about: 'Chi Siamo',
    features: 'Funzionalità',
    pricing: 'Prezzi',
    contact: 'Contatti',
    dashboard: 'Dashboard',
    chat: 'Chat',
    documentChat: 'Chat Documento',
    profile: 'Il Tuo Profilo',
    signIn: 'Accedi',
    signUp: 'Registrati',
    signOut: 'Esci',
    preferredLanguage: 'Lingua Preferita',
    adminDashboard: 'Dashboard Admin',
    adminDashboardDescription: 'Gestisci aziende, contenuti e utenti da una posizione centrale',
    refresh: 'Aggiorna',
    noBusinessesFound: 'Nessuna azienda trovata',
    loginToAltaCoach: 'Accedi a AltaCoach',
    welcomeBack: 'Bentornato',
    rememberMe: 'Ricordami',
    forgotPassword: 'Password dimenticata?',
    selectRole: 'Seleziona Ruolo',
    dontHaveAccount: 'Non hai un account?',
    selectBusiness: 'Seleziona Azienda',
    emailRequired: 'Email è richiesta',
    passwordRequired: 'Password è richiesta',
    invalidCredentials: 'Email o password non validi',
    error: 'Si è verificato un errore. Si prega di riprovare.',
    language: 'Lingua',
    password: 'Password',
    // FAQ translations
    frequentlyAskedQuestions: 'Domande Frequenti',
    canICancel: 'Posso disdire il mio abbonamento in qualsiasi momento?',
    yesYouCan: 'Sì, puoi disdire il tuo abbonamento in qualsiasi momento. Le modifiche saranno visibili nel tuo prossimo ciclo di fatturazione.',
    howManyUsers: 'Quanti utenti posso aggiungere al mio piano?',
    basicAndProfessionalPlans: 'I piani Basic e Professional sono per uso individuale. Per i team, considera il nostro piano Enterprise.',
    whatTypesOfDocuments: 'Quali tipi di documenti supporta AltaCoach?',
    altaCoachSupports: 'AltaCoach supporta file PDF, DOCX, PPT, CSV e di testo. Altri formati saranno aggiunti nei futuri aggiornamenti.',
    isMyDataSecure: 'I miei dati sono sicuri?',
    absolutelyWeTake: 'Assolutamente! Prendiamo sul serio la sicurezza dei dati. Tutti i tuoi documenti e conversazioni sono crittografati e archiviati in modo sicuro.',
    
    // Other missing translations
    custom: 'Personalizzato',
    forLargeOrganizations: 'Per grandi organizzazioni',
    customIntegration: 'Integrazione personalizzata',
    customizableFeatures: 'Funzionalità personalizzabili',
    phone: 'Telefono',
    location: 'Posizione',
    
    // Additional Italian translations
    businesses: 'Aziende',
    content: 'Contenuto',
    userAccounts: 'Account Utenti',
    settings: 'Impostazioni',
    analytics: 'Analytics',
    chatAnalysis: 'Chat Analyse',
    prompts: 'Prompts',
    notifications: 'Benachrichtigungen',
    businessOverview: 'Aperçu des Entreprises',
    activeBusinesses: 'Entreprises Actives',
    pendingBusinesses: 'Entreprises en Attente',
    suspendedBusinesses: 'Entreprises Suspendues',
    contentManagement: 'Gestion de Contenu',
    contentItems: 'Éléments de Contenus',
    exercises: 'Exercices',
    faqs: 'FAQs',
    viewAll: 'Voir Tout',
    manage: 'Gérer',
    approve: 'Approuver',
    suspend: 'Suspendre',
    delete: 'Supprimer',
    userStatistics: 'Statistiques Utilisateurs',
    totalBusinesses: 'Total des Entreprises',
    totalContent: 'Total du Contenu',
    totalUsers: 'Total des Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    adminUsers: 'Utilisateurs Admin',
    courses: 'Cours',
    guides: 'Guides',
    recentRegistrations: 'Inscriptions Récentes',
    selectLanguage: 'Sélectionner la Langue',
    name: 'Nom',
    plan: 'Plan',
    userCount: 'Utilisateurs',
    status: 'État',
    joined: 'Rejoint',
    actions: 'Actions',
    active: 'Actif',
    pending: 'En attente',
    suspended: 'Suspendu',
    view: 'Voir',
    starter: 'Débutant',
    business: 'Entreprise',
    enterprise: 'Enterprise',
    businessAddedSuccessfully: 'Entreprise ajoutée avec succès !',
    errorAddingBusiness: 'Erreur lors de l\'ajout de l\'entreprise. Veuillez réessayer plus tard.',
    businessName: 'Nom de l\'Entreprise',
    email: 'Email',
    phoneNumber: 'Téléphone',
    address: 'Adresse',
    submitting: 'Envoi...',
    add: 'Ajouter',
    cancel: 'Annuler',
    // Settings page translations
    admin: 'Admin',
    settingsDescription: 'Configurer les paramètres de la plateforme et gérer les préférences du système',
    general: 'Général',
    aiPrompts: 'Invites IA',
    apiKeys: 'Clés API',
    generalSettings: 'Paramètres Généraux',
    configureGeneralSettings: 'Configurez les paramètres généraux de votre plateforme.',
    generalSettingsFutureUpdate: 'Les paramètres généraux de la plateforme seront disponibles ici dans une future mise à jour.',
    aiPromptsManagement: 'Gestion des Invites IA',
    addNewPrompt: 'Ajouter une Nouvelle Invite',
    description: 'Description',
    lastUpdated: 'Dernière Mise à Jour',
    noDescription: 'Pas de description',
    inactive: 'Inactif',
    deactivate: 'Désactiver',
    activate: 'Activer',
    noPromptsFound: 'Aucune invite trouvée. Ajoutez votre première invite pour commencer.',
    apiIntegration: 'Intégration API',
    configureApiKeys: 'Configurez les clés API pour les intégrations de services tiers.',
    openaiApiKey: 'Clé API OpenAI',
    openaiApiDescription: 'Configurez votre clé API OpenAI pour activer les fonctionnalités d\'IA. Sans cela, les capacités d\'IA seront limitées.',
    configureApiKey: 'Configurer la Clé API',
    additionalIntegrations: 'Intégrations Supplémentaires',
    moreIntegrationsFuture: 'D\'autres intégrations tierces seront disponibles dans les futures mises à jour.',
    configureOpenaiApiKey: 'Configurer la Clé API OpenAI',
    apiKey: 'Clé API',
    enterApiKeySecure: 'Entrez votre clé API OpenAI. Elle sera stockée en toute sécurité.',
    saving: 'Enregistrement...',
    saveApiKey: 'Enregistrer la Clé API',
    createNewAiPrompt: 'Créer une Nouvelle Invite IA',
    promptName: 'Nom de l\'Invite',
    descriptionOptional: 'Description (Optionnelle)',
    briefDescriptionPrompt: 'Brève description de l\'objectif de l\'invite',
    promptContent: 'Contenu de l\'Invite',
    promptPlaceholder: 'Vous êtes un assistant IA qui aide avec...',
    systemPromptGuide: 'Ceci est l\'invite système qui guidera le comportement de l\'IA.',
    setAsActivePrompt: 'Définir comme invite active',
    oneActivePromptWarning: 'Une seule invite peut être active à la fois. Définir celle-ci comme active désactivera les autres invites.',
    creating: 'Création...',
    createPrompt: 'Créer l\'Invite',
    apiKeyCannotBeEmpty: 'La clé API ne peut pas être vide',
    apiKeySetSuccess: 'Clé API définie avec succès',
    failedToSetApiKey: 'Échec de la définition de la clé API',
    promptNameRequired: 'Le nom de l\'invite est requis',
    promptContentRequired: 'Le contenu de l\'invite est requis',
    failedToCreatePrompt: 'Échec de la création de l\'invite',
    promptCreatedSuccess: 'Invite créée avec succès',
    failedToFetchPrompts: 'Échec de la récupération des invites',
    failedToLoadPrompts: 'Échec du chargement des invites. Veuillez réessayer plus tard.',
    confirmDeletePrompt: 'Êtes-vous sûr de vouloir supprimer cette invite ? Cette action ne peut pas être annulée.',
    failedToDeletePrompt: 'Échec de la suppression de l\'invite',
    confirmDeactivatePrompt: 'Êtes-vous sûr de vouloir désactiver cette invite ?',
    confirmActivatePrompt: 'L\'activation de cette invite désactivera toute invite actuellement active. Continuer ?',
    failedToUpdatePrompt: 'Échec de la mise à jour de l\'invite',
    systemInstructions: 'Instructions Système',
    // Main page translations
    trainingDoesntEnd: 'La Formation Ne S\'arrête Pas en Classe',
    aiPoweredAssistant: 'AltaCoach est votre assistant propulsé par l\'IA pour le soutien post-formation, aidant les employés à appliquer ce qu\'ils ont appris et augmentant la rétention.',
    tryAltaCoach: 'Essayer AltaCoach',
    viewPricing: 'Voir les tarifs',
    postTrainingSupport: 'Support Post-Formation',
    realTimeCoaching: 'Coaching en Temps Réel',
    knowledgeRetention: 'Rétention des Connaissances',
    howReinforces: 'Comment AltaCoach Renforce la Formation',
    aiPoweredPlatform: 'Notre plateforme propulsée par l\'IA fournit un soutien continu après la fin de la formation formelle.',
    aiPoweredQA: 'AI-Powered Q&A',
    employeesCanAsk: 'Les employés peuvent poser des questions et obtenir des réponses instantanées et précises basées sur votre matériel de formation.',
    contentIntegration: 'Intégration de Contenu',
    seamlesslyIntegrates: 'S\'intègre parfaitement à votre contenu de formation et documentation existants.',
    analyticsInsights: 'Analyses et Insights',
    trackEngagement: 'Suivez l\'engagement, identifiez les lacunes de connaissances et mesurez l\'impact de vos initiatives de formation.',
    improvedRetention: 'Rétention Améliorée',
    increaseKnowledge: 'Augmentation de la rétention des connaissances par rapport aux méthodes de formation traditionnelles',
    timeSaved: 'Temps Économisé',
    reductionSearching: 'Réduction du temps passé à rechercher des informations',
    userSatisfaction: 'Satisfaction des Utilisateurs',
    positiveFeedback: 'Retours positifs des employés utilisant la plateforme',
    readyTransform: 'Prêt à transformer votre formation ?',
    joinOrganizations: 'Rejoignez les organisations qui utilisent AltaCoach pour améliorer la rétention et la performance de la formation.',
    getStarted: 'Commencer',
    quickAccess: 'Accès Rapide',
    noLoginRequired: 'Aucune Connexion Requise',
    startSession: 'Démarrer la Session',
    // Contact page translations
    getInTouch: 'Contactez-nous',
    thankYouMessage: 'Merci pour votre message! Nous vous répondrons dès que possible.',
    contactDescription: 'Vous avez des questions ou souhaitez en savoir plus sur AltaCoach? Remplissez le formulaire ci-dessous et notre équipe vous répondra rapidement.',
    yourName: 'Votre nom',
    emailAddress: 'Adresse e-mail',
    subject: 'Sujet',
    message: 'Votre message',
    sending: 'Envoi en cours...',
    sendMessage: 'Envoyer le message',
    errorSubmittingMessage: 'Une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer.',
    
    // Pricing page translations
    choosePerfectPlan: 'Choisissez le forfait parfait pour vos besoins. Tous les forfaits comprennent l\'accès à nos fonctionnalités principales de coaching par IA.',
    basic: 'Basique',
    professional: 'Professionnel',
    forIndividuals: 'Pour les professionnels individuels',
    forGrowingProfessionals: 'Pour les professionnels en croissance',
    forLargeOrganizations: 'Pour les grandes organisations',
    month: 'mois',
    mostPopular: 'LE PLUS POPULAIRE',
    unlimitedAiConversations: 'Conversations IA illimitées',
    uploadUpTo10Documents: 'Téléchargement jusqu\'à 10 documents',
    uploadUpTo50Documents: 'Téléchargement jusqu\'à 50 documents',
    unlimitedDocuments: 'Téléchargement de documents illimité',
    basicProgressTracking: 'Suivi de progression basique',
    emailSupport: 'Support par e-mail',
    everythingInBasic: 'Tout ce qui est inclus dans Basique',
    everythingInProfessional: 'Tout ce qui est inclus dans Professionnel',
    prioritySupport: 'Support prioritaire',
    dedicatedSupport: 'Support dédié',
    customIntegration: 'Intégration personnalisée',
    contactUs: 'Contactez-nous',
    
    // Features page translations
    aiPoweredConversations: 'Conversazioni Potenziate dall\'IA',
    engageInNatural: 'Engagez des conversations naturelles avec notre assistant IA per rafforzare i vostri concetti di formazione e rispondere a domande in tempo reale.',
    documentBasedLearning: 'Apprendimento Basato su Documenti',
    uploadTrainingMaterials: 'Téléchargez vos supports de formation et laissez AltaCoach les traiter pour fournir des informations et des réponses pertinentes dal tuo contenuto.',
    continuousReinforcement: 'Renforcement Continu',
    receiveRegularPrompts: 'Recevez des incitations et des défis réguliers pour renforcer ce que vous avez appris et maintenir les connaissances fraîches au fil du temps.',
    progressTracking: 'Monitoraggio del Progresso',
    monitorYourLearning: 'Monitora il tuo percorso di apprendimento con analisi complete che mostrano coinvolgimento e ritenzione delle conoscenze.',
    howAltaCoachWorks: 'Come Funziona AltaCoach',
    uploadYourMaterials: 'Téléchargez Vos Documents',
    addYourTrainingDocuments: 'Aggiungi i tuoi documenti di formazione per creare una base di conoscenze a cui l\'IA può fare riferimento.',
    engageWithYourCoach: 'Interagisci con il Tuo Coach',
    askQuestions: 'Fai domande e ricevi risposte immediate e personalizzate basate sui tuoi materiali.',
    reinforceAndImprove: 'Rafforza e Migliora',
    receivePersonalizedChallenges: 'Ricevi sfide e prompt personalizzati per rafforzare la ritenzione delle conoscenze.',
    enterpriseFeatures: 'Funzionalità Enterprise',
    teamManagement: 'Gestione del Team',
    createAndManageLearningGroups: 'Crea e gestisci gruppi di apprendimento per monitorare collettivamente i progressi del team.',
    connectAltaCoach: 'Connetti AltaCoach con i tuoi sistemi di gestione dell\'apprendimento esistenti.',
    advancedAnalytics: 'Analisi Avanzate',
    gainInsights: 'Acquisisci informazioni sui modelli di apprendimento e identifica le lacune di conoscenza nei team.',
    customizedLearningPaths: 'Percorsi di Apprendimento Personalizzati',
    designTailoredLearning: 'Progetta esperienze di apprendimento su misura per diversi ruoli e dipartimenti.',
    currentLanguage: 'Lingua Corrente',
  },
  es: {
    welcome: 'Bienvenido',
    home: 'Inicio',
    about: 'Acerca de',
    features: 'Características',
    pricing: 'Precios',
    contact: 'Contacto',
    dashboard: 'Panel de control',
    chat: 'Chat',
    documentChat: 'Chat de Documento',
    profile: 'Tu Perfil',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar sesión',
    preferredLanguage: 'Idioma preferido',
    adminDashboard: 'Panel de Administrador',
    adminDashboardDescription: 'Administre empresas, contenidos y usuarios desde una ubicación central',
    refresh: 'Actualizar',
    noBusinessesFound: 'No se encontraron empresas',
    loginToAltaCoach: 'Iniciar Sesión en AltaCoach',
    welcomeBack: 'Bienvenido de Nuevo',
    rememberMe: 'Recuérdame',
    forgotPassword: '¿Olvidaste tu contraseña?',
    selectRole: 'Seleccionar Rol',
    dontHaveAccount: '¿No tienes una cuenta?',
    selectBusiness: 'Seleccionar Empresa',
    emailRequired: 'El correo electrónico es obligatorio',
    passwordRequired: 'La contraseña es obligatoria',
    invalidCredentials: 'Correo electrónico o contraseña inválidos',
    error: 'Ha ocurrido un error. Por favor, inténtalo de nuevo.',
    language: 'Idioma',
    password: 'Contraseña',
    // FAQ translations
    frequentlyAskedQuestions: 'Preguntas Frecuentes',
    canICancel: '¿Puedo cancelar mi suscripción en cualquier momento?',
    yesYouCan: 'Sí, puedes cancelar tu suscripción en cualquier momento. Los cambios se reflejarán en tu próximo ciclo de facturación.',
    howManyUsers: '¿Cuántos usuarios puedo añadir a mi plan?',
    basicAndProfessionalPlans: 'Los planes Basic y Professional son para uso individual. Para equipos, considera nuestro plan Enterprise.',
    whatTypesOfDocuments: '¿Qué tipos de documentos soporta AltaCoach?',
    altaCoachSupports: 'AltaCoach soporta archivos PDF, DOCX, PPT, CSV y de texto. Se añadirán más formatos en futuras actualizaciones.',
    isMyDataSecure: '¿Están mis datos seguros?',
    absolutelyWeTake: '¡Absolutamente! Nos tomamos en serio la seguridad de los datos. Todos tus documentos y conversaciones están encriptados y almacenados de forma segura.',
    
    // Other missing translations
    custom: 'Personalizado',
    forLargeOrganizations: 'Para grandes organizaciones',
    customIntegration: 'Integración personalizada',
    customizableFeatures: 'Características personalizables',
    phone: 'Teléfono',
    location: 'Ubicación',
    
    // Additional Spanish translations
    businesses: 'Empresas',
    content: 'Contenido',
    userAccounts: 'Cuentas de Usuario',
    settings: 'Configuración',
    analytics: 'Analytics',
    chatAnalysis: 'Chat Analyse',
    prompts: 'Prompts',
    notifications: 'Benachrichtigungen',
    businessOverview: 'Aperçu des Entreprises',
    activeBusinesses: 'Entreprises Actives',
    pendingBusinesses: 'Entreprises en Attente',
    suspendedBusinesses: 'Entreprises Suspendues',
    contentManagement: 'Gestion de Contenu',
    contentItems: 'Éléments de Contenus',
    exercises: 'Exercices',
    faqs: 'FAQs',
    viewAll: 'Voir Tout',
    manage: 'Gérer',
    approve: 'Approuver',
    suspend: 'Suspendre',
    delete: 'Supprimer',
    userStatistics: 'Statistiques Utilisateurs',
    totalBusinesses: 'Total des Entreprises',
    totalContent: 'Total du Contenu',
    totalUsers: 'Total des Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    adminUsers: 'Utilisateurs Admin',
    courses: 'Cours',
    guides: 'Guides',
    recentRegistrations: 'Inscriptions Récentes',
    selectLanguage: 'Sélectionner la Langue',
    name: 'Nom',
    plan: 'Plan',
    userCount: 'Utilisateurs',
    status: 'État',
    joined: 'Rejoint',
    actions: 'Actions',
    active: 'Actif',
    pending: 'En attente',
    suspended: 'Suspendu',
    view: 'Voir',
    starter: 'Débutant',
    business: 'Entreprise',
    enterprise: 'Enterprise',
    businessAddedSuccessfully: 'Entreprise ajoutée avec succès !',
    errorAddingBusiness: 'Erreur lors de l\'ajout de l\'entreprise. Veuillez réessayer plus tard.',
    businessName: 'Nom de l\'Entreprise',
    email: 'Email',
    phoneNumber: 'Téléphone',
    address: 'Adresse',
    submitting: 'Envoi...',
    add: 'Ajouter',
    cancel: 'Annuler',
    // Settings page translations
    admin: 'Admin',
    settingsDescription: 'Configurer les paramètres de la plateforme et gérer les préférences du système',
    general: 'Général',
    aiPrompts: 'Invites IA',
    apiKeys: 'Clés API',
    generalSettings: 'Paramètres Généraux',
    configureGeneralSettings: 'Configurez les paramètres généraux de votre plateforme.',
    generalSettingsFutureUpdate: 'Les paramètres généraux de la plateforme seront disponibles ici dans une future mise à jour.',
    aiPromptsManagement: 'Gestion des Invites IA',
    addNewPrompt: 'Ajouter une Nouvelle Invite',
    description: 'Description',
    lastUpdated: 'Dernière Mise à Jour',
    noDescription: 'Pas de description',
    inactive: 'Inactif',
    deactivate: 'Désactiver',
    activate: 'Activer',
    noPromptsFound: 'Aucune invite trouvée. Ajoutez votre première invite pour commencer.',
    apiIntegration: 'Intégration API',
    configureApiKeys: 'Configurez les clés API pour les intégrations de services tiers.',
    openaiApiKey: 'Clé API OpenAI',
    openaiApiDescription: 'Configurez votre clé API OpenAI pour activer les fonctionnalités d\'IA. Sans cela, les capacités d\'IA seront limitées.',
    configureApiKey: 'Configurer la Clé API',
    additionalIntegrations: 'Intégrations Supplémentaires',
    moreIntegrationsFuture: 'D\'autres intégrations tierces seront disponibles dans les futures mises à jour.',
    configureOpenaiApiKey: 'Configurer la Clé API OpenAI',
    apiKey: 'Clé API',
    enterApiKeySecure: 'Entrez votre clé API OpenAI. Elle sera stockée en toute sécurité.',
    saving: 'Enregistrement...',
    saveApiKey: 'Enregistrer la Clé API',
    createNewAiPrompt: 'Créer une Nouvelle Invite IA',
    promptName: 'Nom de l\'Invite',
    descriptionOptional: 'Description (Optionnelle)',
    briefDescriptionPrompt: 'Brève description de l\'objectif de l\'invite',
    promptContent: 'Contenu de l\'Invite',
    promptPlaceholder: 'Vous êtes un assistant IA qui aide avec...',
    systemPromptGuide: 'Ceci est l\'invite système qui guidera le comportement de l\'IA.',
    setAsActivePrompt: 'Définir comme invite active',
    oneActivePromptWarning: 'Une seule invite peut être active à la fois. Définir celle-ci comme active désactivera les autres invites.',
    creating: 'Création...',
    createPrompt: 'Créer l\'Invite',
    apiKeyCannotBeEmpty: 'La clé API ne peut pas être vide',
    apiKeySetSuccess: 'Clé API définie avec succès',
    failedToSetApiKey: 'Échec de la définition de la clé API',
    promptNameRequired: 'Le nom de l\'invite est requis',
    promptContentRequired: 'Le contenu de l\'invite est requis',
    failedToCreatePrompt: 'Échec de la création de l\'invite',
    promptCreatedSuccess: 'Invite créée avec succès',
    failedToFetchPrompts: 'Échec de la récupération des invites',
    failedToLoadPrompts: 'Échec du chargement des invites. Veuillez réessayer plus tard.',
    confirmDeletePrompt: 'Êtes-vous sûr de vouloir supprimer cette invite ? Cette action ne peut pas être annulée.',
    failedToDeletePrompt: 'Échec de la suppression de l\'invite',
    confirmDeactivatePrompt: 'Êtes-vous sûr de vouloir désactiver cette invite ?',
    confirmActivatePrompt: 'L\'activation de cette invite désactivera toute invite actuellement active. Continuer ?',
    failedToUpdatePrompt: 'Échec de la mise à jour de l\'invite',
    systemInstructions: 'Instructions Système',
    // Main page translations
    trainingDoesntEnd: 'La Formation Ne S\'arrête Pas en Classe',
    aiPoweredAssistant: 'AltaCoach est votre assistant propulsé par l\'IA pour le soutien post-formation, aidant les employés à appliquer ce qu\'ils ont appris et augmentant la rétention.',
    tryAltaCoach: 'Essayer AltaCoach',
    viewPricing: 'Voir les tarifs',
    postTrainingSupport: 'Support Post-Formation',
    realTimeCoaching: 'Coaching en Temps Réel',
    knowledgeRetention: 'Rétention des Connaissances',
    howReinforces: 'Comment AltaCoach Renforce la Formation',
    aiPoweredPlatform: 'Notre plateforme propulsée par l\'IA fournit un soutien continu après la fin de la formation formelle.',
    aiPoweredQA: 'AI-Powered Q&A',
    employeesCanAsk: 'Les employés peuvent poser des questions et obtenir des réponses instantanées et précises basées sur votre matériel de formation.',
    contentIntegration: 'Intégration de Contenu',
    seamlesslyIntegrates: 'S\'intègre parfaitement à votre contenu de formation et documentation existants.',
    analyticsInsights: 'Analyses et Insights',
    trackEngagement: 'Suivez l\'engagement, identifiez les lacunes de connaissances et mesurez l\'impact de vos initiatives de formation.',
    improvedRetention: 'Rétention Améliorée',
    increaseKnowledge: 'Augmentation de la rétention des connaissances par rapport aux méthodes de formation traditionnelles',
    timeSaved: 'Temps Économisé',
    reductionSearching: 'Réduction du temps passé à rechercher des informations',
    userSatisfaction: 'Satisfaction des Utilisateurs',
    positiveFeedback: 'Retours positifs des employés utilisant la plateforme',
    readyTransform: 'Prêt à transformer votre formation ?',
    joinOrganizations: 'Rejoignez les organisations qui utilisent AltaCoach pour améliorer la rétention et la performance de la formation.',
    getStarted: 'Commencer',
    quickAccess: 'Accès Rapide',
    noLoginRequired: 'Aucune Connexion Requise',
    startSession: 'Démarrer la Session',
    // Contact page translations
    getInTouch: 'Contactez-nous',
    thankYouMessage: 'Merci pour votre message! Nous vous répondrons dès que possible.',
    contactDescription: 'Vous avez des questions ou souhaitez en savoir plus sur AltaCoach? Remplissez le formulaire ci-dessous et notre équipe vous répondra rapidement.',
    yourName: 'Votre nom',
    emailAddress: 'Adresse e-mail',
    subject: 'Sujet',
    message: 'Votre message',
    sending: 'Envoi en cours...',
    sendMessage: 'Envoyer le message',
    errorSubmittingMessage: 'Une erreur s\'est produite lors de l\'envoi de votre message. Veuillez réessayer.',
    
    // Pricing page translations
    choosePerfectPlan: 'Choisissez le forfait parfait pour vos besoins. Tous les forfaits comprennent l\'accès à nos fonctionnalités principales de coaching par IA.',
    basic: 'Basique',
    professional: 'Professionnel',
    forIndividuals: 'Pour les professionnels individuels',
    forGrowingProfessionals: 'Pour les professionnels en croissance',
    forLargeOrganizations: 'Pour les grandes organisations',
    month: 'mois',
    mostPopular: 'LE PLUS POPULAIRE',
    unlimitedAiConversations: 'Conversations IA illimitées',
    uploadUpTo10Documents: 'Téléchargement jusqu\'à 10 documents',
    uploadUpTo50Documents: 'Téléchargement jusqu\'à 50 documents',
    unlimitedDocuments: 'Téléchargement de documents illimité',
    basicProgressTracking: 'Suivi de progression basique',
    emailSupport: 'Support par e-mail',
    everythingInBasic: 'Tout ce qui est inclus dans Basique',
    everythingInProfessional: 'Tout ce qui est inclus dans Professionnel',
    prioritySupport: 'Support prioritaire',
    dedicatedSupport: 'Support dédié',
    customIntegration: 'Intégration personnalisée',
    contactUs: 'Contactez-nous',
    
    // Features page translations
    aiPoweredConversations: 'Conversaciones Impulsadas por IA',
    engageInNatural: 'Participe en conversaciones naturales con nuestro asistente de IA para reforzar sus conceptos de formación y responder preguntas en tiempo real.',
    documentBasedLearning: 'Aprendizaje Basado en Documentos',
    uploadTrainingMaterials: 'Téléchargez vos supports de formación y dejez que AltaCoach los procese para proporcionar información y respuestas pertinentes de su contenido.',
    continuousReinforcement: 'Refuerzo Continuo',
    receiveRegularPrompts: 'Reciba mensajes y desafíos regulares para reforzar lo que ha aprendido y mantener el conocimiento fresco a lo largo del tiempo.',
    progressTracking: 'Seguimiento del Progreso',
    monitorYourLearning: 'Supervise su viaje de aprendizaje con análisis completos que muestran el compromiso y la retención de conocimientos.',
    howAltaCoachWorks: 'Cómo Funciona AltaCoach',
    uploadYourMaterials: 'Téléchargez Vos Materiales',
    addYourTrainingDocuments: 'Añada sus documentos de formación para crear una base de conocimientos a la que la IA pueda hacer referencia.',
    engageWithYourCoach: 'Interactúe Con Su Coach',
    askQuestions: 'Haga preguntas y obtenga respuestas inmediatas y personalizadas basadas en sus materiales.',
    reinforceAndImprove: 'Refuerce y Mejore',
    receivePersonalizedChallenges: 'Reciba desafíos y mensajes personalizados para fortalecer la retención de conocimientos.',
    enterpriseFeatures: 'Características Empresariales',
    teamManagement: 'Gestión de Equipo',
    createAndManageLearningGroups: 'Cree y gestione grupos de aprendizaje para seguir colectivamente el progreso del equipo.',
    connectAltaCoach: 'Conecte AltaCoach con sus sistemas de gestión de aprendizaje existentes.',
    advancedAnalytics: 'Análisis Avanzados',
    gainInsights: 'Obtenga información sobre patrones de aprendizaje e identifique brechas de conocimiento en los equipos.',
    customizedLearningPaths: 'Rutas de Aprendizaje Personalizadas',
    designTailoredLearning: 'Diseñe experiencias de aprendizaje adaptadas para diferentes roles y departamentos.',
    currentLanguage: 'Idioma Actual',
  },
};

// Provider component
export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  // Initialize language from user preference or browser locale or default to 'en'
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    
    if (user && 'preferredLanguage' in user && isSupportedLanguage(user.preferredLanguage as string)) {
      setLanguageState(user.preferredLanguage as SupportedLanguage);
    } else if (savedLanguage && isSupportedLanguage(savedLanguage)) {
      setLanguageState(savedLanguage as SupportedLanguage);
    } else {
      // Try to get browser language
      const browserLanguage = navigator.language.split('-')[0];
      if (isSupportedLanguage(browserLanguage)) {
        setLanguageState(browserLanguage as SupportedLanguage);
      }
      // If browser language is not supported, it remains as 'en' default
    }
  }, [user]);

  // Add an event listener for language change events
  useEffect(() => {
    // Log the current language for debugging
    console.log('Current language in effect:', language);
    
    const handleLanguageChanged = (event: Event) => {
      const customEvent = event as CustomEvent<SupportedLanguage>;
      console.log('Language change event detected:', customEvent.detail);
      // Force component re-rendering
      setLanguageState(customEvent.detail);
    };
    
    window.addEventListener('languageChanged', handleLanguageChanged);
    
    return () => {
      window.removeEventListener('languageChanged', handleLanguageChanged);
    };
  }, []);

  // Function to check if a language code is supported
  function isSupportedLanguage(lang: string): lang is SupportedLanguage {
    return Object.keys(translations).includes(lang);
  }

  // Function to set language and save to localStorage
  const setLanguage = async (newLanguage: SupportedLanguage) => {
    console.log('Setting language to:', newLanguage);
    
    // First update local state
    setLanguageState(newLanguage);
    
    // Update local storage
    localStorage.setItem('preferredLanguage', newLanguage);
    
    // Force an immediate UI update by dispatching a custom event
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: newLanguage }));
    
    // Trigger a small timeout to ensure state updates propagate
    setTimeout(() => {
      // Force a re-render by updating state again
      setLanguageState(prevState => {
        if (prevState === newLanguage) {
          // Even if it's the same, force an update to trigger context consumers
          return newLanguage;
        }
        return newLanguage;
      });
    }, 50);
    
    // If user is authenticated, update preference in database
    if (user) {
      try {
        const response = await fetch('/api/user/language', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ 
            language: newLanguage,
            userId: user.id
          }),
        });
        
        if (!response.ok) {
          console.error('Failed to update language preference in database');
        }
      } catch (error) {
        console.error('Error updating language preference:', error);
      }
    }
  };

  // Translation function
  const translate = (key: string, params?: Record<string, string>) => {
    // Log the key and current language for debugging
    if (!translations[language]) {
      console.error(`Language "${language}" not found in translations`);
      // Use English as fallback if language doesn't exist
      const fallbackText = translations.en[key];
      return fallbackText || key;
    }
    
    // First check if the key exists in the current language
    const translatedText = translations[language][key];
    
    // If not found in current language, fall back to English
    const fallbackText = translations.en[key];
    
    // Use the translation, fallback, or the key itself if neither is found
    let text = translatedText || fallbackText || key;
    
    // For debugging - log when a key is missing from the translations
    if (!translatedText) {
      console.warn(`Translation missing for key "${key}" in language "${language}". Using fallback:`, fallbackText || 'KEY ITSELF');
    }
    
    // Replace parameters in the text if provided
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(new RegExp(`{${paramKey}}`, 'g'), value);
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        translate,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

// Hook for using the language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 